### ISSUE TITLE
Says that Firefox Nightly does not support let and const.

### ISSUE THREAD

**Issue by grssam** [ruanyf/es-checker#1]
Am I missing something ? Firefox has supported let and const since very long ago.

**Comment by ruanyf** [comment]
What is the test's result?

https://github.com/ruanyf/es-checker/blob/master/lib/api.js#L2

**Comment by grssam** [comment]
When I try running the following code on any page, no alert comes:

``` js
try {
  new Function("'use strict'; let a; const b = 2;");
} catch (ex) { alert(ex) }
```

**Comment by ruanyf** [comment]
if no alerts, it means your browser supports let/const.

``` javascript
try {
  (new Function("'use strict'; let a; const b = 2;"))();
} catch (ex) { 
  alert(ex) 
}
```

**Comment by grssam** [comment]
http://jsfiddle.net/bpnzduzq/ works. It alerts `NaN`

The only thing is that you have to specifically specify js version as 1.7 or above.

**Comment by ruanyf** [comment]
fixed it.
