### ISSUE TITLE
chrome96探测Module失败

### ISSUE THREAD

**Issue by tangjian1891** [ruanyf/es-checker#15]
打扰您了，请教一下！
发现在支持esm的浏览器上，也显示出 
✖      模块的export命令
✖      模板的import命令

判断浏览器是否支持ESM，是否可以使用以下方式判断。
    <script type="module">
      window.supportESM = true;
    </script>

    <script nomodule>
      window.supportESM = false;
    </script>

      <script>
       setTimeout(() => {
        console.log("是否支持supportESM", window.supportESM);
       }, 1000);
      </script>

我发现普通<script>标签即使放在<script type="module">下方，执行顺序也会快一点，所以增加了1个1秒延迟打印查看。

**Comment by ruanyf** [comment]
你的方法可行，但是这个库不打算更新了。
