### ISSUE TITLE
是不是可以增加监测对象 -  浏览器的信息

### ISSUE THREAD

**Issue by sjy** [ruanyf/es-checker#3]
运行es-checker会监测系统默认浏览器对es 6的支持程度， 为了更加友好和严谨，建议在回显信息中加入浏览器的信息

**Comment by ruanyf** [comment]
浏览器信息可以直接在Navigator对象上取到，我觉得放在es-checker里面意义不大。而且，除了浏览器，es-checker还支持其他环境。
